.TH cutmidel "1" "November 15, 2020" "" "cutmidel manual"

.SH NAME
cutmidel - trims a text with an ellipsis

.SH SYNOPSIS
.B cutmidel
[-V|--version] [-h|--help]
.RS
.I <text>
.I <leading>
.I <trailing>
.I [ellipsis]

.SH DESCRIPTION
cutmidel trims a text to a maximum length by putting an ellipsis to the middle of the shortened result.

.SH OPTIONS
.B
.IP "-V, --version"
prints the version of the executable and exits
.B
.IP "-h, --help"
prints the usage information and exits

.in
Specify the text and the maximum count of leading and trailing
characters. The overall maximum length will be their sum plus
the length of an ellipsis (3 dots by default). Zero for either leading
or trailing count means no leading or trailing parts.

.SH EXAMPLES
 $ cutmidel "~/Sources/private/cutmidel" 5 10
 ~/Sou...e/cutmidel
 $ cutmidel ~/Sources/private/cutmidel 0 12 ..
 ..ate/cutmidel

.SH BUGS
cutmidel's bug tracker is located at <https://github.com/prantlf/cutmidel/issues>

.SH DOCUMENTATION
See the website for documentation <https://prantlf.github.io/cutmidel/>

.SH AUTHOR
Currently maintained by Ferdinand Prantl <prantlf@gmail.com>
